INSERT INTO member (full_name, bio, email, joined_at, number_of_rsvps) VALUES
('Eleftherios Chrysochoidis', 'Community organizer & Java enthusiast. Spring Boot advocate.', 'eleftherios.chrysochoidis@example.com', '2012-03-15', 58),
('Nikolaos Papadopoulos', 'Backend developer specializing in microservices and Kafka.', 'nikolaos.papadopoulos@example.com', '2013-06-20', 45),
('Aikaterini Georgiou', 'Full-stack developer with a passion for reactive systems.', 'aikaterini.georgiou@example.com', '2014-01-10', 52),
('Dimitrios Vlahos', 'Software architect at a fintech startup. Loves JVM internals.', 'dimitrios.vlahos@example.com', '2012-09-05', 61),
('Maria Konstantinou', 'DevOps engineer. Kubernetes and CI/CD pipelines enthusiast.', 'maria.konstantinou@example.com', '2015-11-22', 38),
('Georgios Alexiou', 'Data engineer working with Apache Spark and Flink.', 'georgios.alexiou@example.com', '2016-04-18', 29),
('Sophia Papadaki', 'Junior developer learning Spring AI and LLM integrations.', 'sophia.papadaki@example.com', '2023-09-01', 5),
('Ioannis Stavridis', 'Tech lead at a logistics company. Distributed systems fan.', 'ioannis.stavridis@example.com', '2013-02-28', 47),
('Christina Economou', 'Mobile developer transitioning to backend with Spring Boot.', 'christina.economou@example.com', '2019-07-14', 18),
('Panagiotis Theodorou', 'Security engineer and OWASP contributor.', 'panagiotis.theodorou@example.com', '2014-08-30', 41),
('Evangelia Katsarou', 'QA automation engineer. Selenium and Testcontainers advocate.', 'evangelia.katsarou@example.com', '2017-05-12', 25),
('Konstantinos Makris', 'Freelance consultant specializing in legacy modernization.', 'konstantinos.makris@example.com', '2012-11-03', 55),
('Anastasia Nikolaou', 'PhD student researching AI-assisted code generation.', 'anastasia.nikolaou@example.com', '2022-01-20', 9),
('Alexandros Doukas', 'Platform engineer building internal developer tools.', 'alexandros.doukas@example.com', '2015-03-08', 34),
('Vasiliki Hatzigeorgiou', 'Database administrator with deep PostgreSQL expertise.', 'vasiliki.hatzigeorgiou@example.com', '2018-10-25', 21),
('Christos Papanikolaou', 'Embedded systems developer curious about cloud-native Java.', 'christos.papanikolaou@example.com', '2020-06-15', 14),
('Eleni Sourla', 'Scrum master and part-time developer. Community volunteer.', 'eleni.sourla@example.com', '2016-12-01', 31),
('Stefanos Antoniadis', 'Game developer exploring server-side Java with Quarkus.', 'stefanos.antoniadis@example.com', '2021-04-10', 11),
('Despoina Karagianni', 'Front-end specialist attending to learn about backend patterns.', 'despoina.karagianni@example.com', '2024-02-14', 3),
('Theodoros Manolis', 'Retired professor. Attends every meetup since the early days.', 'theodoros.manolis@example.com', '2012-03-15', 60);
